const en = {
  hero: {
    breadcrumbHome: 'Home',
    breadcrumbCurrent: 'Investor Relations',
    eyebrow: 'Investor Relations',
    title: 'Transparent Corporate Governance',
    lead: 'Committed to transparency, accountability, and sustainable long-term value creation for all stakeholders.',
    pillars: [
      { v: '10', l: 'Operating divisions' },
      { v: '4', l: 'Governance bodies' },
      { v: '15+', l: 'Countries served' },
    ],
  },
  info: {
    eyebrow: 'INVESTOR INFORMATION',
    title1: 'Start with the',
    title2: 'right information.',
    lead: 'Request current company information, financial reporting and the supporting documents relevant to your discussion.',
    mark: 'N71',
    introTitle: 'Discuss your due diligence requirements.',
    introText: 'Our team can clarify which documents are available and the appropriate process for sharing them.',
    cta: 'Request information ↗',
    steps: ['Brief', 'Availability', 'Secure sharing'],
  },
  thesis: {
    eyebrow: 'Why Invest',
    title: 'Investment Thesis',
    items: [
      {
        id: 'portfolio',
        title: 'Diversified Portfolio',
        desc: 'Ten distinct business divisions — from garments and maritime to technology, media and strategic ventures — reduce concentration risk and create multiple vectors for growth and resilience.',
      },
      {
        id: 'markets',
        title: 'Emerging Market Access',
        desc: 'Deep roots in South Asia with growing reach across the Middle East, Africa, and Southeast Asia — regions forecast for sustained economic expansion.',
      },
      {
        id: 'technology',
        title: 'Technology-Led Growth',
        desc: 'Our Ezyify platform and IT division embed technology across all operations, enabling scalable, data-driven management and new digital revenue streams.',
      },
    ],
  },
  documents: {
    eyebrow: 'Resources',
    title: 'Documents & Filings',
    availability: 'Ask about current availability',
    request: 'Request details ↗',
    items: [
      { name: 'Company overview', subject: 'Company overview request' },
      { name: 'Financial reporting', subject: 'Financial reporting request' },
      { name: 'Investment information', subject: 'Investment information request' },
    ],
  },
  governance: {
    eyebrow: 'Governance',
    title: 'Board Structure',
    p1: 'Network71 maintains a formal governance structure dedicated to accountability, transparency, and sound corporate stewardship across all divisions and geographies.',
    note: 'Board composition and governance details to be published.',
    pending: 'To be published',
    bodies: [
      'Board of Directors',
      'Audit Committee',
      'Risk Committee',
      'ESG Committee',
    ],
  },
  facts: {
    eyebrow: 'Investment Proposition',
    title1: 'The Frame,',
    title2: 'Before the Conversation',
    lead: 'The parameters a capital partner asks about first. Indicative; every structure is set out in a term sheet after due diligence.',
    facts: [
      { value: 'Private', unit: '', label: 'Status', sub: 'Founder-led group, no public listing; growth capital raised at group or division level' },
      { value: '3', unit: ' vehicles', label: 'Ways to invest', sub: 'Division equity, joint-venture co-investment, project or trade finance' },
      { value: '0.5–10', unit: ' M USD', label: 'Ticket range', sub: 'Larger with co-investors or for group-level rounds' },
      { value: '5–10', unit: ' yrs', label: 'Horizon', sub: 'Long-term operator capital; exits planned, never forced' },
      { value: '10', unit: ' divisions', label: 'Exposure', sub: 'One group, ten operating businesses across five regions' },
      { value: '90', unit: ' days', label: 'Screen to term sheet', sub: 'Typical elapsed time with a prepared data room' },
    ],
    note: 'Not an offer of securities. Information is provided to qualified counterparties under NDA.',
    cta: 'Request the information pack',
  },
  vehicles: {
    eyebrow: 'Ways to Invest',
    title1: 'Three Routes',
    title2: 'into the Group',
    lead: 'Capital enters at the level where it does the most work — a single division, a co-owned venture, or a specific trade or project. Select a route to see how it is structured.',
    rowsLabel: ['Instrument', 'Typical ticket', 'Governance', 'Returns', 'Horizon & exit'],
    items: [
      { id: 'equity', code: 'DE', name: 'Division equity', desc: 'A minority stake in one operating division — garments, agro, oils, IT, media, maritime.', cells: ['Ordinary or preferred shares in the division entity', 'USD 1–10 M', 'Board seat or observer, information & consent rights', 'Dividends per division policy plus capital appreciation', '5–10 yrs; put/call at fair value, secondary, strategic sale'] },
      { id: 'jv', code: 'JV', name: 'Joint-venture co-investment', desc: 'Co-own a new business with Network71 and an operating partner via the Strategic Ventures division.', cells: ['NewCo equity alongside N71 and partner', 'USD 0.5–5 M', 'Joint board, reserved matters, deadlock clause', 'Pro-rata share of NewCo distributions and exit', '5–7 yrs; ROFR, IPO or trade sale, spin-out'] },
      { id: 'trade', code: 'TF', name: 'Project & trade finance', desc: 'Fund specific import/export cycles or capital projects against contracts and collateral.', cells: ['Structured loan, LC discounting, revenue share', 'USD 0.5–3 M per facility', 'Covenants, reporting per drawdown, security package', 'Fixed coupon or margin share; self-liquidating', '3–18 months per cycle; renewable'] },
    ],
    footnote: 'Terms shown are typical positions. Definitive terms are set in the subscription, shareholders’ or facility agreement.',
  },
  allocation: {
    eyebrow: 'Use of Capital',
    title1: 'Where Growth Capital',
    title2: 'Goes to Work',
    lead: 'Indicative allocation of a group-level growth round across the current plan. Division-level rounds are ring-fenced to that division.',
    total: '100 %',
    totalLabel: 'of a group growth round',
    items: [
      { id: 'capacity', label: 'Manufacturing & processing capacity', pct: 35, color: 'var(--accent-rose)', desc: 'Garments lines, agro processing and F&B production; oil storage and packing.' },
      { id: 'tech', label: 'Technology & Ezyify', pct: 25, color: 'var(--accent-cyan)', desc: 'Platform engineering, AI features, ERP roll-out across divisions.' },
      { id: 'working', label: 'Trade working capital', pct: 20, color: 'var(--accent-blue)', desc: 'Inventory and receivables for Global Trading, Oils and Agro export cycles.' },
      { id: 'markets', label: 'Market entry & ventures', pct: 15, color: 'var(--accent-indigo)', desc: 'Corridor offices, JV formation and market-entry programmes.' },
      { id: 'reserve', label: 'Governance & reserve', pct: 5, color: 'var(--brand)', desc: 'Audit, compliance systems and a liquidity buffer.' },
    ],
    footnote: 'Illustrative plan; final allocation is agreed with investors at term-sheet stage and reported quarterly.',
  },
  reporting: {
    eyebrow: 'Reporting & Disclosure',
    title1: 'What Investors',
    title2: 'Receive, and When',
    lead: 'Reporting is contractual, not discretionary. Every investor agreement sets out the cadence below as an obligation.',
    items: [
      { period: 'Monthly', title: 'Flash report', desc: 'Revenue, gross margin, cash position and order book per division. Within 15 days of month-end.' },
      { period: 'Quarterly', title: 'Management accounts & board pack', desc: 'Unaudited P&L, balance sheet, cash flow, KPIs versus plan; risk register and committee minutes.' },
      { period: 'Annually', title: 'Audited financial statements', desc: 'Group and division accounts audited by an independent firm; ESG summary; governance report.' },
      { period: 'Event-driven', title: 'Material disclosures', desc: 'Change of control, key-person departure, litigation, covenant breach — within five business days.' },
    ],
    accessLabel: 'Access',
    access: ['Secure investor data room', 'Quarterly investor call', 'Annual general meeting', 'Direct line to Investor Relations'],
    footnote: 'Cadence applies to equity investors; facility-level reporting follows the finance agreement.',
  },
  diligence: {
    eyebrow: 'Due Diligence',
    title1: 'From First Call',
    title2: 'to Signed Terms',
    lead: 'What happens in each window, what we provide and what we need from you.',
    stages: [
      { code: 'D1', title: 'Introduction', window: 'Week 1', we: 'Information pack: group overview, division summaries, headline financials', you: 'Mandate, ticket range, investment horizon' },
      { code: 'D2', title: 'NDA & data room', window: 'Week 1–2', we: 'NDA, data-room access with indexed documents', you: 'Signed NDA, named deal team' },
      { code: 'D3', title: 'Management meetings', window: 'Week 2–5', we: 'Division heads, site visits, customer and supplier references', you: 'Question list, follow-up requests' },
      { code: 'D4', title: 'Commercial, financial & legal DD', window: 'Week 4–10', we: 'Full access, audit workpapers, legal and compliance disclosures', you: 'Advisers, red-flag report, valuation view' },
      { code: 'D5', title: 'Term sheet', window: 'Week 10–13', we: 'Structure, governance rights, reporting covenants, exit provisions', you: 'Investment committee approval, exclusivity' },
    ],
    labels: { we: 'We provide', you: 'You provide' },
    indexLabel: 'Data-room index',
    index: ['Corporate documents & cap table', 'Three-year financials & management accounts', 'Division KPIs & order books', 'Material contracts & licences', 'Tax, legal & compliance disclosures', 'Management CVs & org charts', 'ESG, labour & safety records'],
    footnote: 'Timelines assume a prepared data room; cross-border approvals may extend the term-sheet window.',
  },
  faq: {
    eyebrow: 'Investor FAQ',
    title1: 'Questions We',
    title2: 'Hear First',
    lead: 'Short answers on status, structure, reporting, exit and how to start.',
    items: [
      { q: 'Is Network71 publicly listed?', a: 'No. Network71 Ltd is a privately held, founder-led group headquartered in Dhaka. There is no public market for its shares; investment is by private agreement with qualified counterparties.' },
      { q: 'Can I invest in a single division rather than the group?', a: 'Yes. Division equity is the most common route: a minority stake in one operating division with its own board seat, information rights and dividend policy. Group-level rounds are offered periodically.' },
      { q: 'What minimum ticket do you consider?', a: 'Indicatively USD 500 k for trade finance or JV co-investment and USD 1 M for division equity. Smaller amounts are pooled where a lead investor is in place.' },
      { q: 'How is investor protection handled?', a: 'Information and consent rights, reserved matters, anti-dilution and tag/drag provisions are written into the shareholders’ agreement. Facility investors receive a security package and covenants.' },
      { q: 'What reporting will I receive?', a: 'Monthly flash reports, quarterly management accounts and board packs, annual audited statements and event-driven disclosures — all as contractual obligations, delivered through a secure data room.' },
      { q: 'What is the exit route?', a: 'Agreed at term-sheet stage: put/call options at fair value, right of first refusal, secondary sale to a strategic or financial investor, or an IPO of a division when scale allows. Target horizon five to ten years.' },
      { q: 'Are the figures on this site audited?', a: 'Figures on public pages describe the group structure and plan; they are not audited financials. Audited statements are shared in the data room under NDA.' },
      { q: 'How do I start?', a: 'Send an enquiry with your mandate and ticket range. Investor Relations replies within two business days with the information pack and an NDA.' },
    ],
    cta: 'Start an enquiry',
  },
  enquiry: {
    eyebrow: 'Contact',
    title: 'Investor Enquiry',
    lead: 'Send your questions and the documents you would like to review.',
    email: 'investors@network71.com',
    direct: 'Direct investor enquiries',
    sentTitle: 'Enquiry Received',
    sentText: 'Your investor enquiry has been saved. Reference: {ref}',
    form: {
      name: 'Full Name *',
      namePlaceholder: 'Jane Smith',
      company: 'Company *',
      companyPlaceholder: 'Acme Capital',
      email: 'Email *',
      emailPlaceholder: 'jane@example.com',
      range: 'Investment Range',
      rangeOptions: [
        { value: 'Not specified', label: 'Not specified' },
        { value: 'Under $100K', label: 'Under $100K' },
        { value: '$100K – $500K', label: '$100K – $500K' },
        { value: '$500K – $1M', label: '$500K – $1M' },
        { value: '$1M+', label: '$1M+' },
      ],
      inquiry: 'Type of Enquiry *',
      inquiryOptions: [
        { value: 'General Inquiry', label: 'General Inquiry' },
        { value: 'Investment Discussion', label: 'Investment Discussion' },
        { value: 'Partnership', label: 'Partnership' },
        { value: 'Media', label: 'Media' },
      ],
      message: 'Message *',
      messagePlaceholder: 'Tell us about your enquiry…',
      submit: 'Send Enquiry',
    },
  },
}

export type InvestorsContent = typeof en
export default en
