import {
  metrics,
  pillars,
  productCategories,
  brandModels,
  standards,
  processSteps,
} from './en/data-a'
import {
  facilities,
  qualityMetrics,
  certifications,
  sustainability,
  exportMarkets,
  opportunities,
  roadmap,
} from './en/data-b'

const en = {
  divisionName: 'Food & Beverage Manufacturing',
  processLabel: 'From Concept to Consumer',
  inquiryTypes: ['Retail Distribution', 'Export Buyer', 'Co-Manufacturing', 'Private Label', 'B2B Supply'],
  metrics,
  pillars,
  productCategories,
  brandModels,
  standards,
  processSteps,
  facilities,
  qualityMetrics,
  certifications,
  sustainability,
  exportMarkets,
  opportunities,
  roadmap,
  hero: {
    image: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=1400&h=800&fit=crop&auto=format',
    eyebrow: 'Network71 — Food & Beverage Division',
    title1: 'Food & Beverage',
    title2: 'Manufacturing',
    lead: 'Food and beverage manufacturing from Bangladesh, built for domestic retail and export shelves.',
    ctaPrimary: 'Partner With Us',
    ctaSecondary: 'View Product Range',
    imgAlt: 'Food manufacturing facility',
  },
  partnerTerms: {
    eyebrow: 'Partnering With Us',
    title1: 'The Numbers Retail Buyers',
    title2: 'Ask For First',
    lead: 'Indicative commercial frame for private-label and co-manufacturing programmes — confirmed per SKU in the proposal.',
    facts: [
      { value: '5,000', unit: ' units', label: 'Indicative MOQ / SKU', sub: 'Per flavour and pack size; pilot batches from 1,000 units' },
      { value: '4–6', unit: ' weeks', label: 'NPD to gold sample', sub: 'Brief → bench sample → sensory panel → approved gold standard' },
      { value: '6–8', unit: ' weeks', label: 'First production run', sub: 'From gold-sample sign-off and artwork approval' },
      { value: '9–18', unit: ' months', label: 'Shelf life', sub: 'Ambient lines; chilled 21–45 days, frozen 12 months' },
      { value: '12', unit: ' formats', label: 'Packaging formats', sub: 'Pouch, sachet, jar, can, PET, Tetra, carton, tray and bulk' },
      { value: 'LC', unit: ' / TT', label: 'Payment', sub: 'Export: sight LC; domestic and co-man: 30% advance, balance on dispatch' },
    ],
    note: 'Planning values; each SKU is confirmed in the commercial proposal after formulation and packaging are fixed.',
    cta: 'Start a private-label brief',
  },
  npd: {
    eyebrow: 'New Product Development',
    title1: 'From Brief',
    title2: 'to Shelf',
    lead: 'How a private-label or co-manufacturing product moves through our kitchen and onto the line — every gate has a deliverable you sign off.',
    stages: [
      { code: 'S1', title: 'Brief & Benchmark', weeks: 'Week 0–1', desc: 'Target consumer, price point, benchmark product, claims, pack format and launch date captured in a one-page brief.', deliverable: 'Signed brief + costing range' },
      { code: 'S2', title: 'Bench Formulation', weeks: 'Week 1–3', desc: 'Food technologists build 2–3 bench variants; ingredient declarations and allergen matrix drafted alongside.', deliverable: 'Bench samples + spec draft' },
      { code: 'S3', title: 'Sensory & Iteration', weeks: 'Week 3–4', desc: 'Trained panel scores taste, texture and appearance against the benchmark; up to two revision rounds.', deliverable: 'Sensory report + gold sample' },
      { code: 'S4', title: 'Shelf-Life & Compliance', weeks: 'Week 4–8', desc: 'Accelerated and real-time stability, microbiological baseline, nutrition panel and destination labelling review (BSTI, halal, importer rules).', deliverable: 'Shelf-life dossier + label proof' },
      { code: 'S5', title: 'Pilot Batch', weeks: 'Week 8–10', desc: 'Line trial at production scale; packaging seal, fill weight and code-dating validated. Saleable pilot stock for listings.', deliverable: 'Pilot QC record + sell-in samples' },
      { code: 'S6', title: 'Commercial Run', weeks: 'Week 10+', desc: 'First commercial batch under the agreed spec; CoA per batch, retained samples and traceability record issued with dispatch.', deliverable: 'CoA + dispatch pack' },
    ],
    footnote: 'Timelines are typical for ambient dry and liquid lines; chilled and frozen programmes add stability time.',
  },
  formats: {
    eyebrow: 'Packaging Formats',
    title: 'Retail-Ready Formats We Run',
    lead: 'Pack formats configured per category — sizes and materials fixed with the buyer at the NPD stage.',
    items: [
      { icon: '🥡', name: 'Stand-up pouch', sizes: '50 g – 1 kg', for: 'Snacks, spice blends, premixes' },
      { icon: '🧂', name: 'Sachet / stick', sizes: '3 – 30 g', for: 'Seasonings, drink mixes, single-serve' },
      { icon: '🫙', name: 'Glass jar', sizes: '150 – 750 g', for: 'Sauces, pickles, condiments' },
      { icon: '🥫', name: 'Can', sizes: '200 – 850 g', for: 'Ready meals, pulses, fruit' },
      { icon: '🧴', name: 'PET bottle', sizes: '250 ml – 2 L', for: 'Juices, drinks, oils' },
      { icon: '🧃', name: 'Aseptic carton', sizes: '200 ml – 1 L', for: 'Nectars, RTD, dairy alternatives' },
      { icon: '📦', name: 'Folding carton', sizes: '100 – 500 g', for: 'Biscuits, bakery, confectionery' },
      { icon: '🧊', name: 'Frozen tray', sizes: '250 g – 1 kg', for: 'Frozen prepared foods' },
      { icon: '🛢️', name: 'Bulk / food-service', sizes: '5 – 25 kg', for: 'HORECA, industrial, re-pack' },
    ],
    note: 'Printed or labelled options for every format; recyclable mono-material films available on request.',
  },
  faq: {
    eyebrow: 'Buyer FAQ',
    title1: 'Questions Retail & Export',
    title2: 'Buyers Ask First',
    lead: 'Straight answers on private label, minimums, food safety and how a listing goes from brief to first delivery.',
    items: [
      { q: 'Can you match an existing product on our shelf?', a: 'Yes. Send the benchmark product or its spec; our technologists reverse-formulate to taste, texture and cost target, then adjust to your positioning. Bench samples typically ship within three weeks of the brief.' },
      { q: 'What is the minimum order per SKU?', a: 'Indicatively 5,000 units per flavour and pack size for ambient lines, with pilot batches from 1,000 units for market testing. Chilled and frozen lines are quoted per format.' },
      { q: 'Which food-safety frameworks do you work to?', a: 'The readiness roadmap references ISO 22000, HACCP, GMP and product-level halal certification. Status is published only with documentary evidence — ask for the current position in your enquiry and we will share the audit file.' },
      { q: 'How is shelf life established?', a: 'Accelerated and real-time stability studies per formulation, with microbiological baselines and packaging integrity tests. The shelf-life dossier is part of the S4 gate before any pilot batch.' },
      { q: 'Do you support export labelling and documentation?', a: 'Yes — nutrition panels, allergen declarations and destination labelling (BSTI, GCC, EU) are drafted during NPD, and each export dispatch ships with CoA, halal documentation where certified, certificate of origin and packing list.' },
      { q: 'Can we audit the facility?', a: 'Buyer and third-party audits are welcome. Choose "Private Label" or "Co-Manufacturing" in the enquiry form and mention an audit; we will share the pre-audit pack and arrange dates.' },
      { q: 'Who owns the recipe?', a: 'For private label, formulations developed to your brief are yours under a confidential manufacturing agreement. For co-manufacturing, your existing recipe stays yours; we operate it under NDA and quality parity terms.' },
    ],
    cta: 'Ask something else',
  },
  overview: {
    eyebrow: 'Our Vision',
    title1: 'Manufacturing Built to Standard,',
    title2: 'From Bangladesh to',
    title3: 'Global Shelves',
    p1: 'Network71 is developing a Food & Beverage division spanning product planning, sourcing and retail-ready packaging. Current facilities, approvals and production scope require confirmation.',
    p2: 'Our ambition is to establish Network71 as a trusted FMCG manufacturer from Bangladesh: supplying domestic retail, developing proprietary brands, and placing products on international shelves across the Middle East, Europe, and beyond.',
    positioningLabel: 'Key positioning:',
    positioning: 'A roadmap for product-level approvals, food-safety documentation and export readiness.',
    pillarsTitle: 'Brand Pillars',
  },
  products: {
    linesLabel: 'product lines',
    eyebrow: 'Product Portfolio',
    title: 'What We Manufacture',
    lead: 'A comprehensive food and beverage range designed for multiple consumer segments, retail channels, and export markets.',
  },
  brandModelsCopy: {
    eyebrow: 'Brand Development',
    title1: 'Three Brand Models,',
    title2: 'One Manufacturing Partner',
    lead: 'A key differentiator of the N71 Food & Beverage division is our ability to operate across three distinct brand models — serving our own brands, retail partners, and manufacturing clients simultaneously.',
    highlightTag: 'Key Differentiator',
  },
  standardsCopy: {
    eyebrow: 'Manufacturing Standards',
    title1: 'Standards',
    title2: 'Readiness Roadmap',
    lead: 'These are target frameworks. Current certification, laboratory and facility status will be published only with approved evidence.',
    labTitle: 'Quality Laboratory',
    labLead: 'The planned testing scope is listed below; current in-house and third-party capability requires confirmation.',
    labItems: [
      'Microbiological analysis (bacteria, yeast, mould)',
      'Chemical composition and nutritional testing',
      'Sensory evaluation panels',
      'Shelf-life and stability studies',
      'Allergen management and testing',
      'Packaging integrity and seal testing',
    ],
    labNote: 'Third-party laboratory verification available on request. Contact division for current testing scope.',
  },
  facilitiesCopy: {
    eyebrow: 'Facilities',
    title: 'Three Processing Units',
    lead: 'Each unit is configured for a specific product category cluster, with dedicated food-safety and quality systems.',
    colUnit: 'Processing Unit',
    colCapacity: 'Capacity',
    colLines: 'Product Lines',
    colCerts: 'Target frameworks',
    qcEyebrow: 'On-Site Laboratory & QC',
    qcTitle: 'Integrated Quality Control',
    qcItems: ['Incoming QC', 'In-Process QC', 'Finished Goods QC', 'Environmental Monitoring'],
    qcLead: 'Each processing unit is supported by on-site quality control infrastructure. Lab results directly gate production release — no batch leaves without QC sign-off.',
  },
  quality: {
    eyebrow: 'Standards & Frameworks',
    title: 'Quality & Compliance',
    lead: 'Our manufacturing operations work to multiple food-safety frameworks — supporting confidence for retail buyers, export partners, and regulators.',
    note: 'Current status of each framework and formal compliance documentation are available from the division on request.',
    targetsEyebrow: 'Performance Targets',
    targetsTitle1: 'Measurable Quality',
    targetsTitle2: 'Standards',
    cultureTitle: 'Continuous Improvement Culture',
    cultureLead: 'Performance metrics are reviewed monthly against targets. Non-conformances trigger root-cause analysis and corrective action within defined SLAs. Third-party audits are welcomed as validation of our internal quality management posture.',
  },
  supplyChain: {
    eyebrow: 'Supply Chain',
    title: 'End-to-End Supply Chain',
    lead: 'From verified raw material suppliers through controlled manufacturing to domestic and export distribution — an integrated value chain.',
    sourcingTitle: 'Raw Material Sourcing',
    sourcingLead: 'Primary ingredient sourcing from Bangladeshi farms and manufacturers — supporting local agriculture with direct procurement relationships.',
    sourcingItems: [
      'Local Bangladesh raw materials (primary)',
      'Imported specialty ingredients (supplementary)',
      'Approved supplier audits and quality agreements',
      'Dual-source strategy for critical ingredients',
    ],
    distributionTitle: 'Distribution Reach',
    distributionLead: 'Products distributed through domestic retail networks and export logistics partners — covering modern trade, traditional retail, and international channels.',
    distributionItems: [
      'Bangladesh domestic retail (modern & traditional trade)',
      'Export consolidation via Dhaka and Chittagong',
      'Cold-chain distribution for temperature-sensitive products',
      'Halal export documentation and compliance',
    ],
  },
  sustainabilityCopy: {
    eyebrow: 'Sustainability',
    title: 'Responsible Manufacturing',
    lead: 'Building a food manufacturing division that is commercially sound and environmentally responsible — for people, planet, and future consumers.',
  },
  exportMarketsCopy: {
    eyebrow: 'Export Markets',
    title1: 'Bangladesh to',
    title2: 'Global Retail',
    lead: 'Export requirements vary by product and destination. Halal, BSTI and food-safety documentation will be confirmed for each opportunity before any market claim is made.',
    cta: 'Export Buyer Inquiry',
  },
  opportunitiesCopy: {
    eyebrow: 'Business Opportunities',
    title1: 'Partner With Our',
    title2: 'Food Division',
    lead: 'We are actively seeking partners across four business models. If your business aligns with any of these, we want to hear from you.',
  },
  roadmapCopy: {
    eyebrow: 'Growth Roadmap',
    title: 'The Path to Global Shelves',
    lead: 'A four-year plan taking the Food & Beverage division from manufacturing foundations to own-brand international retail listing.',
  },
}

export type FoodBeverageContent = typeof en
export default en
