import {
  metrics,
  pillars,
  productCategories,
  brandModels,
  standards,
  processSteps,
} from './en/data-a'
import {
  facilities,
  qualityMetrics,
  certifications,
  sustainability,
  exportMarkets,
  opportunities,
  roadmap,
} from './en/data-b'

const en = {
  divisionName: 'Food & Beverage Manufacturing',
  processLabel: 'From Concept to Consumer',
  inquiryTypes: ['Retail Distribution', 'Export Buyer', 'Co-Manufacturing', 'Private Label', 'B2B Supply'],
  metrics,
  pillars,
  productCategories,
  brandModels,
  standards,
  processSteps,
  facilities,
  qualityMetrics,
  certifications,
  sustainability,
  exportMarkets,
  opportunities,
  roadmap,
  hero: {
    eyebrow: 'Network71 — Food & Beverage Division',
    title1: 'Food & Beverage',
    title2: 'Manufacturing',
    lead: 'Food and beverage manufacturing from Bangladesh, built for domestic retail and export shelves.',
    ctaPrimary: 'Partner With Us',
    ctaSecondary: 'View Product Range',
    imgAlt: 'Food manufacturing facility',
  },
  overview: {
    eyebrow: 'Our Vision',
    title1: 'Manufacturing Built to Standard,',
    title2: 'From Bangladesh to',
    title3: 'Global Shelves',
    p1: 'Network71\'s Food & Beverage division operates manufacturing facilities built around recognised food-safety systems, producing a range of food and beverage products — from raw ingredient sourcing through to retail-ready packaging.',
    p2: 'Our ambition is to establish Network71 as a trusted FMCG manufacturer from Bangladesh: supplying domestic retail, developing proprietary brands, and placing products on international shelves across the Middle East, Europe, and beyond.',
    positioningLabel: 'Key positioning:',
    positioning: 'Halal-compliant processes, international food-safety systems and export-ready documentation — competitive on quality, not just price.',
    pillarsTitle: 'Brand Pillars',
  },
  products: {
    eyebrow: 'Product Portfolio',
    title: 'What We Manufacture',
    lead: 'A comprehensive food and beverage range designed for multiple consumer segments, retail channels, and export markets.',
  },
  brandModelsCopy: {
    eyebrow: 'Brand Development',
    title1: 'Three Brand Models,',
    title2: 'One Manufacturing Partner',
    lead: 'A key differentiator of the N71 Food & Beverage division is our ability to operate across three distinct brand models — serving our own brands, retail partners, and manufacturing clients simultaneously.',
    highlightTag: 'Key Differentiator',
  },
  standardsCopy: {
    eyebrow: 'Manufacturing Standards',
    title1: 'Built to',
    title2: 'Recognised Standards',
    lead: 'Our facilities are built around internationally recognised food safety management systems. Standards are not a box-tick — they are embedded in our daily production operations.',
    labTitle: 'Quality Laboratory',
    labLead: 'In-house laboratory capability supports pre-production, in-line, and finished goods testing across our product range.',
    labItems: [
      'Microbiological analysis (bacteria, yeast, mould)',
      'Chemical composition and nutritional testing',
      'Sensory evaluation panels',
      'Shelf-life and stability studies',
      'Allergen management and testing',
      'Packaging integrity and seal testing',
    ],
    labNote: 'Third-party laboratory verification available on request. Contact division for current testing scope.',
  },
  facilitiesCopy: {
    eyebrow: 'Facilities',
    title: 'Three Processing Units',
    lead: 'Each unit is configured for a specific product category cluster, with dedicated food-safety and quality systems.',
    colUnit: 'Processing Unit',
    colCapacity: 'Capacity',
    colLines: 'Product Lines',
    colCerts: 'Standards applied',
    qcEyebrow: 'On-Site Laboratory & QC',
    qcTitle: 'Integrated Quality Control',
    qcItems: ['Incoming QC', 'In-Process QC', 'Finished Goods QC', 'Environmental Monitoring'],
    qcLead: 'Each processing unit is supported by on-site quality control infrastructure. Lab results directly gate production release — no batch leaves without QC sign-off.',
  },
  quality: {
    eyebrow: 'Standards & Frameworks',
    title: 'Quality & Compliance',
    lead: 'Our manufacturing operations work to multiple food-safety frameworks — supporting confidence for retail buyers, export partners, and regulators.',
    note: 'Current status of each framework and formal compliance documentation are available from the division on request.',
    targetsEyebrow: 'Performance Targets',
    targetsTitle1: 'Measurable Quality',
    targetsTitle2: 'Standards',
    cultureTitle: 'Continuous Improvement Culture',
    cultureLead: 'Performance metrics are reviewed monthly against targets. Non-conformances trigger root-cause analysis and corrective action within defined SLAs. Third-party audits are welcomed as validation of our internal quality management posture.',
  },
  supplyChain: {
    eyebrow: 'Supply Chain',
    title: 'End-to-End Supply Chain',
    lead: 'From verified raw material suppliers through controlled manufacturing to domestic and export distribution — an integrated value chain.',
    sourcingTitle: 'Raw Material Sourcing',
    sourcingLead: 'Primary ingredient sourcing from Bangladeshi farms and manufacturers — supporting local agriculture with direct procurement relationships.',
    sourcingItems: [
      'Local Bangladesh raw materials (primary)',
      'Imported specialty ingredients (supplementary)',
      'Approved supplier audits and quality agreements',
      'Dual-source strategy for critical ingredients',
    ],
    distributionTitle: 'Distribution Reach',
    distributionLead: 'Products distributed through domestic retail networks and export logistics partners — covering modern trade, traditional retail, and international channels.',
    distributionItems: [
      'Bangladesh domestic retail (modern & traditional trade)',
      'Export consolidation via Dhaka and Chittagong',
      'Cold-chain distribution for temperature-sensitive products',
      'Halal export documentation and compliance',
    ],
  },
  sustainabilityCopy: {
    eyebrow: 'Sustainability',
    title: 'Responsible Manufacturing',
    lead: 'Building a food manufacturing division that is commercially sound and environmentally responsible — for people, planet, and future consumers.',
  },
  exportMarketsCopy: {
    eyebrow: 'Export Markets',
    title1: 'Bangladesh to',
    title2: 'Global Retail',
    lead: 'Our halal-compliant processes, BSTI registration where applicable, and international food safety systems position Network71 products for placement in key export markets — particularly where Bangladeshi diaspora and halal consumer segments drive FMCG demand.',
    cta: 'Export Buyer Inquiry',
  },
  opportunitiesCopy: {
    eyebrow: 'Business Opportunities',
    title1: 'Partner With Our',
    title2: 'Food Division',
    lead: 'We are actively seeking partners across four business models. If your business aligns with any of these, we want to hear from you.',
  },
  roadmapCopy: {
    eyebrow: 'Growth Roadmap',
    title: 'The Path to Global Shelves',
    lead: 'A four-year plan taking the Food & Beverage division from manufacturing foundations to own-brand international retail listing.',
  },
}

export type FoodBeverageContent = typeof en
export default en
