const en = {
  hero: {
    breadcrumbHome: 'Home',
    breadcrumbCurrent: 'About',
    eyebrow: 'Our Story',
    title: 'About Network71',
    lead: "Building tomorrow's global enterprise, today.",
    facts: [
      { value: '2018', label: 'Founded in Dhaka' },
      { value: '10', label: 'Business divisions' },
      { value: 'One', label: 'Unified ecosystem' },
    ],
    visionLines: ['Building Businesses.', 'Connecting Markets.', 'Creating the Future.'],
    visionLabel: 'Our vision',
  },
  story: {
    eyebrow: 'Our Origins',
    title: 'From Dhaka to the World',
    p1: 'Network71 was founded in 2018 in Dhaka, Bangladesh. What began as a trading company with a clear vision has grown into a diversified enterprise — spanning ten business divisions and international markets.',
    p2: 'Our journey is rooted in a belief that emerging markets hold extraordinary potential. By combining local expertise with global networks, we build bridges between communities, businesses, and opportunity — from South Asia to the world.',
    p3: 'Today, Network71 operates ten business divisions — from garments and agriculture to technology, media and maritime — united by a shared commitment to excellence, sustainability, and long-term value creation for every stakeholder we serve.',
    imageSrc: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&h=700&fit=crop&auto=format',
    imageAlt: 'Modern office district — illustrative image',
    divisions: [
      'Garments & Apparel',
      'Agriculture & Agro',
      'Food & Beverage',
      'Oils & Energy',
      'IT & Software',
      'Global Trading',
      'Strategic Ventures',
      'Media',
      'eSHIPe Maritime',
      'Ezyify',
    ],
    activeLabel: 'Active Divisions',
    activeValue: '10 Divisions',
    activeSub: 'Headquartered in Dhaka, trading across three focus regions',
  },
  purpose: {
    eyebrow: 'Purpose',
    title: 'Vision & Mission',
    vision: {
      label: 'Vision',
      title: 'A Trusted Multinational',
      text: 'To become a trusted multinational enterprise contributing to economic transformation across emerging markets.',
    },
    mission: {
      label: 'Mission',
      title: 'Sustainable Value',
      text: 'To create sustainable value through diversified industry leadership, innovation, and global connectivity.',
    },
  },
  quote: {
    text: 'We are building more than a company — we are building a bridge between emerging markets and global opportunity.',
    initial: 'T',
    name: 'Tanjijur Rahman Topon',
    role: 'Founder & CEO, Network71',
  },
  values: {
    eyebrow: 'Principles',
    title: 'Core Values',
    items: [
      { id: 'integrity', title: 'Integrity', desc: 'Honest dealings in every market we serve.', color: '#C8962A' },
      { id: 'innovation', title: 'Innovation', desc: 'Technology and fresh thinking at our core.', color: 'var(--accent-cyan)' },
      { id: 'collaboration', title: 'Collaboration', desc: 'Partners, teams, and communities unified.', color: 'var(--accent-teal)' },
      { id: 'excellence', title: 'Excellence', desc: 'Consistent, high standards across all divisions.', color: '#C8962A' },
      { id: 'sustainability', title: 'Sustainability', desc: 'Building responsibly for future generations.', color: 'var(--accent-teal)' },
    ],
  },
  leadership: {
    eyebrow: 'Team',
    title: 'Leadership',
    viewAll: 'View Full Team →',
    note: 'Further executive appointments are published here once confirmed.',
    people: [
      { name: 'Tanjijur Rahman Topon', title: 'Founder & CEO' },
    ],
  },
  timeline: {
    eyebrow: 'History',
    title: 'Our Journey',
    entries: [
      {
        year: '2018',
        title: 'Founded',
        detail: 'Network71 established in Dhaka, Bangladesh. Began with trading operations, laying the groundwork for a diversified global enterprise.',
        side: 'left',
      },
      {
        year: '2019',
        title: 'First Manufacturing Facility',
        detail: 'Opened our first manufacturing facility, accelerating production capacity and establishing Network71 as a credible industrial operator.',
        side: 'right',
      },
      {
        year: '2020',
        title: 'Multi-Sector Portfolio',
        detail: 'Added Food & Beverage and Oils & Energy divisions, building a resilient multi-sector portfolio and diversified revenue base.',
        side: 'left',
      },
      {
        year: '2021',
        title: 'Five Divisions Established',
        detail: 'Expanded to five business divisions including IT & Software — beginning the technology transformation that would define our next chapter.',
        side: 'right',
      },
      {
        year: '2022',
        title: 'International Scale',
        detail: 'Trade network extended across the Middle East, Europe, and Southeast Asia, with new export and sourcing relationships.',
        side: 'left',
      },
      {
        year: '2023',
        title: 'Ezyify AI Platform Launched',
        detail: 'Launched Ezyify — an AI-powered global e-commerce and social media ecosystem. A landmark step in our technology-led growth strategy.',
        side: 'right',
      },
      {
        year: '2024',
        title: 'Today',
        detail: 'Ten business divisions — including Media, Ship Marketplace and Strategic Ventures — operating from Dhaka with trade partners across South Asia, the Middle East and Southeast Asia.',
        side: 'left',
      },
    ],
  },
  glance: {
    eyebrow: 'At a Glance',
    title1: 'The Group,',
    title2: 'in Six Facts',
    lead: 'What a partner, journalist or candidate usually asks first — in one place.',
    facts: [
      { value: '2018', unit: '', label: 'Founded', sub: 'Dhaka, Bangladesh; began as a trading company' },
      { value: '10', unit: ' divisions', label: 'Operating businesses', sub: 'Garments to maritime, technology to media — one ecosystem' },
      { value: '5', unit: ' regions', label: 'Trading footprint', sub: 'South Asia, Middle East, Europe, Southeast Asia, Africa' },
      { value: '1', unit: ' HQ', label: 'Headquarters', sub: 'Dhaka; regional representation coordinated from here' },
      { value: 'Private', unit: '', label: 'Ownership', sub: 'Founder-led; no public listing — see Investor Relations' },
      { value: '4', unit: ' policies', label: 'Group governance', sub: 'Code of Conduct, Anti-Corruption, Data Privacy, Whistleblower' },
    ],
    note: 'Figures describe the group structure, not audited financials.',
    cta: 'Talk to us',
  },
  name: {
    eyebrow: 'The Name',
    title1: 'Why',
    title2: '"71"',
    lead: 'The number is not a version or a postcode. It is the year Bangladesh became a country — and the spirit we want every business we build to carry.',
    numeral: '71',
    notes: [
      { k: '1971', title: 'Independence', desc: 'The year of Bangladesh’s liberation. Ambition, self-reliance and building from first principles.' },
      { k: 'Network', title: 'Connection', desc: 'A group whose divisions are stronger together — manufacturing feeds trade, trade feeds technology, media tells the story.' },
      { k: '71 →', title: 'Forward', desc: 'The badge is red for a reason: momentum. Every new division, venture and market is another chapter of the same idea.' },
    ],
  },
  ecosystem: {
    eyebrow: 'How the Group Works',
    title1: 'One Core,',
    title2: 'Ten Orbits',
    lead: 'Divisions are operating businesses with their own P&L. Around a shared core — finance, legal, people, technology and brand — they trade capability with each other. Select a division to see what it gives and what it draws on.',
    coreLabel: 'Shared core',
    core: ['Finance & treasury', 'Legal & compliance', 'People & HR', 'Technology (IT & Software)', 'Brand & media'],
    givesLabel: 'Gives the group',
    drawsLabel: 'Draws on',
    nodes: [
      { id: 'garments', name: 'Garments & Apparel', short: 'Garments', href: '/divisions/garments', color: 'var(--accent-rose)', gives: 'Export volume, factory base and buyer relationships in Europe and North America.', draws: 'Trading corridors, IT production systems, media for brand.' },
      { id: 'agri', name: 'Agriculture & Agro', short: 'Agro', href: '/divisions/agriculture', color: 'var(--accent-green)', gives: 'Raw materials for food processing and export commodities for trading.', draws: 'Logistics, cold chain, trade finance, agri-tech tools.' },
      { id: 'food', name: 'Food & Beverage', short: 'F&B', href: '/divisions/food-beverage', color: 'var(--accent-amber)', gives: 'Consumer brands and processed goods for regional distribution.', draws: 'Agro inputs, edible oils, packaging sourcing, media advertising.' },
      { id: 'oils', name: 'Oils & Energy', short: 'Oils', href: '/divisions/oils-energy', color: 'var(--accent-orange)', gives: 'Edible oils to F&B, industrial fuel to factories and fleets.', draws: 'Import corridors, storage logistics, trade finance.' },
      { id: 'it', name: 'IT & Software', short: 'IT', href: '/divisions/it-software', color: 'var(--accent-cyan)', gives: 'Every platform the group runs on — ERP, Ezyify, eSHIPe, newsroom systems.', draws: 'Real operating problems to solve; enterprise clients through divisions.' },
      { id: 'trading', name: 'Global Trading', short: 'Trading', href: '/divisions/global-trading', color: 'var(--accent-blue)', gives: 'Corridors, freight, documentation and market access for every product division.', draws: 'Volume from garments, agro, oils; Ezyify for digital trade.' },
      { id: 'media', name: 'Media', short: 'Media', href: '/divisions/media', color: 'var(--accent-purple)', gives: 'Newsroom, TV and digital reach; editorially independent of the group.', draws: 'IT platforms, advertising demand from consumer divisions.' },
      { id: 'eshipe', name: 'eSHIPe Maritime', short: 'eSHIPe', href: '/divisions/eshipe', color: 'var(--accent-sky)', gives: 'Vessel sale-and-purchase marketplace and maritime expertise.', draws: 'Trading network for buyers and sellers, IT for the platform.' },
      { id: 'ventures', name: 'Strategic Ventures', short: 'Ventures', href: '/divisions/strategic-ventures', color: 'var(--accent-indigo)', gives: 'New businesses, joint ventures and market entry for every division.', draws: 'Operating depth of all nine divisions as its diligence and launch bench.' },
      { id: 'ezyify', name: 'Ezyify', short: 'Ezyify', href: '/ezyify', color: 'var(--accent-pink)', gives: 'AI-powered commerce and social platform; the group’s consumer front door.', draws: 'IT engineering, product supply from divisions, media for growth.' },
    ],
    footnote: 'Media operates with editorial independence from commercial and group interests.',
  },
  explore: {
    eyebrow: 'Go Deeper',
    title: 'How We Are Run, Where We Operate, What We Stand For',
    items: [
      { k: '01', title: 'Corporate Governance', desc: 'Board oversight, risk management, compliance and the four group policies every employee signs.', href: '/governance', cta: 'Governance framework' },
      { k: '02', title: 'Global Presence', desc: 'Five regions, principal trade corridors and how each market fits the value chain.', href: '/global-presence', cta: 'See the map' },
      { k: '03', title: 'Sustainability & ESG', desc: 'Commitments, community programmes and the UN SDGs we report against.', href: '/sustainability', cta: 'Our commitments' },
      { k: '04', title: 'Brand & Press', desc: 'The 71 badge, logo files and colour system for partners and journalists.', href: '/brand', cta: 'Brand identity' },
    ],
  },
  faq: {
    eyebrow: 'Common Questions',
    title1: 'About',
    title2: 'Network71',
    lead: 'Short answers to what partners, candidates and journalists ask us most.',
    items: [
      { q: 'Who owns Network71?', a: 'Network71 Ltd is a privately held, founder-led group headquartered in Dhaka. It is not listed on any stock exchange. Investor and partnership enquiries are handled by Investor Relations and the Strategic Ventures division.' },
      { q: 'Is Network71 one company or many?', a: 'One group, ten operating divisions. Each division runs its own business and P&L, and shares a common core — finance, legal, people, technology and brand — so a partner working with one division can draw on the rest.' },
      { q: 'Where does the “71” come from?', a: 'From 1971, the year of Bangladesh’s independence. The name is a commitment to build businesses from Bangladesh that compete anywhere.' },
      { q: 'Where do you operate?', a: 'Headquarters and manufacturing are in Bangladesh. We trade across South Asia, the Middle East, Europe, Southeast Asia and Africa. Regional representation is coordinated from Dhaka; contact us for a representative in your market.' },
      { q: 'How is the media division kept independent?', a: 'Network71 Media’s newsroom operates with full editorial independence from commercial and group interests. Commercial partnerships and press enquiries go through separate desks.' },
      { q: 'How do I partner, invest or join?', a: 'Partnerships: start with the relevant division page or Strategic Ventures. Investment: Investor Relations. Careers: open roles are listed on the Careers page, and we welcome speculative applications.' },
      { q: 'Can I use the Network71 logo or quote the company?', a: 'Yes, within the brand guidelines on the Brand page. For quotes, interviews and press materials, contact the newsroom desk listed on the Press page.' },
    ],
    cta: 'Ask us directly',
  },
  cta: {
    title: 'Join Our Global Team',
    text: "Be part of the team that's shaping the future of emerging markets.",
    primary: 'Explore Careers',
    secondary: 'Get in Touch',
  },
}

export type AboutContent = typeof en
export default en
