import { RED, GOLD } from '../theme'

const en = {
  divisionName: 'Media',
  hero: {
    eyebrow: 'Network71 — Division 09',
    strip: 'NETWORK71 MEDIA',
    stripSub: 'Digital storytelling & editorial enquiries',
    title1: 'Where News Meets',
    title2: 'the World.',
    lead: "Network71 Media is the Group's dedicated media division — delivering credible, independent, and high-quality journalism across digital news and broadcast television. Serving audiences across South Asia, the Middle East, and beyond.",
    ctaPrimary: 'Media Partnerships',
    ctaSecondary: 'View Programmes',
    live: 'Live Schedule',
    stats: [
      { v: '24/7', l: 'Broadcast' },
      { v: 'Multi', l: 'Platform' },
      { v: 'Digital + TV', l: 'Platforms' },
    ],
    terminal: {
      command: '$ n71-media --channel=live --stream=active',
      checks: ['broadcast signal confirmed', 'editorial desk online', 'digital & broadcast desks online'],
      status: 'transmitting_',
    },
  },
  metrics: [
    { value: 'Live', label: 'Broadcasting', desc: '24/7 news & programme delivery' },
    { value: 'Multi', label: 'Platform', desc: 'Digital, mobile & broadcast' },
    { value: 'Regional', label: 'Audience', desc: 'South Asia, Middle East & diaspora' },
    { value: 'Two', label: 'Platforms', desc: 'Digital newspaper and TV channel' },
  ],
  overview: {
    eyebrow: 'Division Overview',
    title: 'Independent Media for a Connected World',
    p1: 'Network71 Media operates two parallel channels of content delivery: a digital news portal and mobile platform providing real-time reporting, analysis, and multimedia journalism; and a dedicated television channel broadcasting 24 hours a day, 7 days a week.',
    p2: 'Editorial independence is the non-negotiable foundation of our media operations. Our newsroom operates with full separation from commercial and group interests, upholding the highest standards of accuracy, verification, and public accountability. The division serves audiences across South Asia, the Middle East, Southeast Asia, and diaspora communities worldwide.',
    platforms: [
      { name: 'Digital News Portal', desc: 'Web-first news platform with real-time updates, multimedia content, and personalised feeds.', color: RED },
      { name: 'Mobile App', desc: 'Native iOS and Android app delivering breaking alerts, live streams, and saved articles.', color: 'var(--accent-cyan)' },
      { name: 'TV Channel', desc: '24/7 live broadcast channel with rolling news, scheduled programmes, and live specials.', color: GOLD },
      { name: 'Video & VOD', desc: 'Full video-on-demand library, including long-form documentaries and archived broadcasts.', color: 'var(--accent-purple)' },
    ],
  },
  desks: {
    eyebrow: 'Editorial Coverage',
    title: 'Six Coverage Desks',
    lead: 'Our editorial team is organised across six specialist desks — each staffed by dedicated journalists and editors with deep subject expertise.',
    items: [
      { title: 'Breaking News', desc: 'Real-time reporting on major world events. Verified, fast, and ethically sourced from correspondents and wire partners across our coverage regions.', color: RED },
      { title: 'Business & Economy', desc: 'In-depth analysis of global markets, trade policy, corporate developments, and emerging economic trends.', color: GOLD },
      { title: 'International Affairs', desc: 'Comprehensive international news coverage including geopolitics, diplomacy, and cross-border developments.', color: 'var(--accent-cyan)' },
      { title: 'Technology', desc: 'Innovation, AI, startups, digital transformation, and the technology forces reshaping industries worldwide.', color: 'var(--accent-purple)' },
      { title: 'Culture & Society', desc: 'Arts, heritage, social movements, sports, and the stories that define communities at home and in the diaspora.', color: 'var(--accent-emerald)' },
      { title: 'Investigative Reporting', desc: 'Long-form investigative journalism — uncovering stories that matter with evidence, rigour, and independence.', color: 'var(--accent-orange)' },
    ],
  },
  tv: {
    badge: 'Network71 TV — Live 24/7',
    title1: 'Broadcast Television.',
    title2: 'Around the Clock.',
    p1: 'Network71 TV is a dedicated 24-hour news and current affairs channel broadcasting live coverage, scheduled news bulletins, analysis programmes, and investigative documentaries. The channel serves our regional audiences and is distributed across cable, satellite, and digital streaming platforms.',
    p2: 'Programme scheduling, carriage agreements, and distribution reach details will be published as broadcast partnerships are confirmed.',
    signalTitle: 'Broadcast Signal Status',
    signals: [
      { label: 'Digital Streaming', status: 'Active', color: 'var(--accent-green)' },
      { label: 'Cable Distribution', status: 'In Negotiation', color: GOLD },
      { label: 'Satellite Coverage', status: 'In Progress', color: GOLD },
      { label: 'Mobile Live', status: 'Active', color: 'var(--accent-green)' },
    ],
    scheduleTitle: 'Programme Schedule',
    scheduleNote: '* Schedule subject to change. Full listings published on official channel guides.',
    programmes: [
      { title: 'The Daily Brief', time: 'Mon – Fri  |  07:00', format: 'Morning news programme', color: RED },
      { title: 'Markets Watch', time: 'Daily  |  09:30', format: 'Business & financial markets', color: GOLD },
      { title: 'World Report', time: 'Daily  |  12:00', format: 'Midday international news', color: 'var(--accent-cyan)' },
      { title: 'Evening Edition', time: 'Daily  |  18:30', format: 'Evening flagship bulletin', color: RED },
      { title: 'The Insight', time: 'Weekly', format: 'Long-form investigative feature', color: 'var(--accent-purple)' },
      { title: 'Economy Plus', time: 'Weekly', format: 'Global trade & economic affairs', color: GOLD },
      { title: 'Tech Horizon', time: 'Weekly', format: 'Technology & innovation desk', color: 'var(--accent-emerald)' },
      { title: 'Press Review', time: 'Daily  |  22:00', format: 'Media analysis & review', color: 'var(--fg-muted)' },
    ],
  },
  standards: {
    eyebrow: 'Editorial Charter',
    title: 'Journalism Built on Trust',
    lead: 'In an era of accelerating misinformation, our editorial charter is a public commitment — not merely an internal policy. Every story Network71 Media publishes is held to the same standard: independently verified, fairly presented, and subject to immediate correction when found to be in error.',
    items: [
      { title: 'Editorial Independence', desc: 'News operations are editorially independent from commercial interests and group divisions.' },
      { title: 'Verified Sourcing', desc: 'Every story is cross-referenced with a minimum of two independent sources before publication.' },
      { title: 'Corrections Policy', desc: 'Corrections are published promptly and prominently — accountability is non-negotiable.' },
      { title: 'Privacy & Ethics', desc: 'Strict adherence to journalistic ethics, data privacy laws, and international press standards.' },
    ],
  },
  advertising: {
    eyebrow: 'Commercial Opportunities',
    title: 'Reach Our Audiences',
    lead: 'Network71 Media provides advertising and partnership opportunities across digital, mobile, and television platforms — connecting brands with engaged, informed audiences.',
    cta: 'Enquire Now',
    items: [
      { title: 'Display Advertising', tag: 'Digital', desc: 'Premium display placements across the Network71 Media digital portfolio including news portal, mobile app, and video player pre/mid-rolls.', color: RED },
      { title: 'Broadcast Sponsorship', tag: 'TV', desc: 'Named sponsorship of flagship programmes — brand exposure across our 24/7 TV channel, with audience reporting shared as distribution partnerships are confirmed.', color: GOLD },
      { title: 'Strategic Content Partnership', tag: 'Branded Content', desc: 'Custom editorial content, advertorials, and co-produced features that integrate brand messaging within a clearly labelled editorial context.', color: 'var(--accent-cyan)' },
    ],
  },
  gallery: {
    eyebrow: 'Media Gallery',
    title: 'From the Newsroom',
    cta: 'View Full Gallery',
    brand: 'Network71 Media',
    note: 'Gallery content updated regularly. All editorial imagery is sourced from licensed and original photography.',
    items: [
      { img: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=600&h=400&fit=crop&auto=format', label: 'Breaking News Desk' },
      { img: 'https://images.unsplash.com/photo-1586339949216-35c2747cc36d?w=600&h=400&fit=crop&auto=format', label: 'Broadcast Studio' },
      { img: 'https://images.unsplash.com/photo-1495020689067-958852a7765e?w=600&h=400&fit=crop&auto=format', label: 'Field Reporting' },
      { img: 'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=600&h=400&fit=crop&auto=format', label: 'Digital News Portal' },
      { img: 'https://images.unsplash.com/photo-1561736778-92e52a7769ef?w=600&h=400&fit=crop&auto=format', label: 'Business Desk' },
      { img: 'https://images.unsplash.com/photo-1478737270239-2f02b77fc618?w=600&h=400&fit=crop&auto=format', label: 'International Coverage' },
    ],
  },
  adSpecs: {
    eyebrow: 'Ad Formats & Specs',
    title1: 'Every Placement,',
    title2: 'Spec’d Before You Ask',
    lead: 'Digital, video and broadcast formats with the creative requirements and lead times a media planner needs on the first call.',
    groups: [
      { key: 'digital', label: 'Digital display', color: 'var(--accent-red)' },
      { key: 'video', label: 'Video & pre-roll', color: 'var(--accent-cyan)' },
      { key: 'tv', label: 'Broadcast', color: 'var(--brand-fg)' },
      { key: 'branded', label: 'Branded content', color: 'var(--accent-purple)' },
    ],
    labels: { size: 'Size / duration', file: 'File & weight', lead: 'Lead time', where: 'Runs on' },
    items: [
      { group: 'digital', name: 'Billboard', size: '970 × 250', file: 'JPG / HTML5 · ≤ 200 KB', lead: '5 working days', where: 'Portal desktop, article top' },
      { group: 'digital', name: 'MPU / Double MPU', size: '300 × 250 · 300 × 600', file: 'JPG / HTML5 · ≤ 200 KB', lead: '5 working days', where: 'Portal, app, AMP' },
      { group: 'digital', name: 'Mobile interscroller', size: 'Responsive 9:16', file: 'PNG / MP4 · ≤ 2 MB', lead: '10 working days', where: 'Mobile web & app' },
      { group: 'digital', name: 'Newsletter sponsorship', size: '600 × 200 + 60 words', file: 'PNG · ≤ 150 KB', lead: '3 working days', where: 'Daily Brief email' },
      { group: 'video', name: 'Pre-roll', size: '15 s · 30 s', file: 'MP4 H.264 · 1080p · ≤ 50 MB', lead: '5 working days', where: 'Portal & app player' },
      { group: 'video', name: 'Mid-roll', size: '30 s', file: 'MP4 H.264 · 1080p', lead: '5 working days', where: 'Long-form & VOD' },
      { group: 'video', name: 'Live-stream bumper', size: '6 s · 10 s', file: 'MP4 · 1080p · no audio', lead: '7 working days', where: 'Live stream breaks' },
      { group: 'tv', name: 'Spot advertising', size: '15 s · 30 s · 45 s', file: 'MXF / ProRes · 1080i50 · -23 LUFS', lead: '10 working days', where: 'Ad breaks, all dayparts' },
      { group: 'tv', name: 'Programme sponsorship', size: '5 s open + 5 s close', file: 'ProRes 4444 · alpha', lead: '15 working days', where: 'Named flagship programmes' },
      { group: 'tv', name: 'Ticker / L-band', size: 'Lower-third strip', file: 'PNG sequence · alpha', lead: '7 working days', where: 'Rolling news blocks' },
      { group: 'branded', name: 'Sponsored feature', size: '800–1,200 words + 3 images', file: 'DOCX · JPG ≥ 1600 px', lead: '10 working days', where: 'Portal, clearly labelled' },
      { group: 'branded', name: 'Co-produced video', size: '2–6 min', file: 'Brief → our production', lead: '4–6 weeks', where: 'Portal, YouTube, TV feature slot' },
    ],
    footnote: 'Audio must be user-initiated on digital; creatives are tested before go-live. Rate card shared on request.',
    cta: 'Request the rate card',
  },
  audience: {
    eyebrow: 'Audience',
    title1: 'Who You Reach',
    title2: 'on Network71 Media',
    lead: 'Indicative audience profile across portal, app and TV. Measured figures are shared in the media kit as distribution partnerships confirm.',
    segments: [
      { label: 'Business & finance decision-makers', pct: 34 },
      { label: 'Diaspora households (GCC, UK, EU)', pct: 28 },
      { label: 'Students & young professionals', pct: 22 },
      { label: 'Public sector & policy', pct: 16 },
    ],
    regions: [
      { flag: '🇧🇩', name: 'Bangladesh', share: 'Home market' },
      { flag: '🇦🇪', name: 'GCC', share: 'Largest diaspora' },
      { flag: '🇬🇧', name: 'UK & EU', share: 'Premium segment' },
      { flag: '🇲🇾', name: 'Southeast Asia', share: 'Growing' },
    ],
    platforms: [
      { label: 'Mobile', pct: 68 },
      { label: 'Desktop', pct: 22 },
      { label: 'Connected TV / OTT', pct: 10 },
    ],
    footnote: 'Targets for the launch year; audited figures replace these as measurement partnerships go live.',
  },
  production: {
    eyebrow: 'Production Services',
    title1: 'A Newsroom',
    title2: 'You Can Hire',
    lead: 'Studio, crew and post-production for brands, agencies and partner broadcasters — the same team that runs the channel.',
    items: [
      { icon: '🎙️', title: 'Studio hire', desc: 'Two-camera news studio with lighting grid, teleprompter and live-streaming uplink.', turnaround: 'Half-day / full-day', from: 'Bookable from 4 h' },
      { icon: '📹', title: 'Field crew', desc: 'Camera operator, sound and producer for interviews, events and corporate coverage across Bangladesh.', turnaround: 'Same-week', from: 'Half-day minimum' },
      { icon: '✂️', title: 'Post-production', desc: 'Edit, colour, graphics and subtitles in Bangla and English; broadcast-safe delivery.', turnaround: '3–7 working days', from: 'Per minute of finished video' },
      { icon: '📡', title: 'Live event streaming', desc: 'Multi-camera live production with graphics, simulcast to your channels and ours.', turnaround: '2 weeks notice', from: 'Per event' },
      { icon: '🗞️', title: 'Corporate & annual-report video', desc: 'Scripted brand films, leadership interviews and results explainers with an editorial eye.', turnaround: '4–6 weeks', from: 'Per project' },
      { icon: '🎧', title: 'Podcast production', desc: 'Recording, editing, hosting and distribution for branded or partner podcasts.', turnaround: 'Weekly episodes', from: 'Series retainer' },
    ],
    labels: { turnaround: 'Turnaround', from: 'Booking' },
    cta: 'Request a production quote',
  },
  pressDesk: {
    eyebrow: 'Press & Newsroom',
    title1: 'Talk to the',
    title2: 'Newsroom',
    lead: 'How to reach the right desk — for tips, corrections, credentials and interview requests. Editorial contacts are independent of the commercial team.',
    channels: [
      { icon: '⚡', title: 'News tips & story ideas', desc: 'Send tips to the breaking desk. We protect sources and verify before publication.', sla: 'Acknowledged within 24 h' },
      { icon: '✎', title: 'Corrections', desc: 'Report an error in any story. Corrections run promptly and are noted on the article.', sla: 'Reviewed within 48 h' },
      { icon: '🪪', title: 'Press credentials', desc: 'Accreditation for journalists, photographers and partner broadcasters covering our events.', sla: '5 working days' },
      { icon: '🎤', title: 'Interview & spokesperson requests', desc: 'Request an interview with Network71 leadership or a Media division editor.', sla: 'Response within 2 working days' },
    ],
    note: 'For advertising and sponsorship use the commercial form below; editorial decisions are never influenced by commercial enquiries.',
    cta: 'Contact the newsroom',
  },
  faq: {
    eyebrow: 'Advertiser & Partner FAQ',
    title1: 'Before You',
    title2: 'Book a Campaign',
    lead: 'Straight answers on formats, lead times, audience reporting, branded content rules and how to work with the newsroom.',
    items: [
      { q: 'What formats can we book and how much notice do you need?', a: 'Display (billboard, MPU, interscroller, newsletter), video (pre-roll, mid-roll, live bumpers), broadcast (spots, sponsorship idents, L-band) and branded content. Lead times run from 3 working days for newsletter to 15 working days for sponsorship idents — the spec table above lists each.' },
      { q: 'How do you report campaign performance?', a: 'Digital campaigns report impressions, viewability, clicks and video completion from the ad server, weekly and at wrap. Broadcast reporting follows the measurement partnerships confirmed per carriage agreement and is shared in the media kit.' },
      { q: 'Is branded content marked as such?', a: 'Always. Sponsored features and co-produced video carry a visible “Sponsored” or “In partnership with” label, sit outside the news desks’ workflow and are approved by the commercial editor, not the newsroom.' },
      { q: 'Can we sponsor a specific programme?', a: 'Yes — flagship programmes (The Daily Brief, Markets Watch, Evening Edition and the weekly features) are available for named sponsorship with open/close idents, break bumpers and digital extensions. Availability is confirmed per quarter.' },
      { q: 'Do you produce content for brands that do not advertise?', a: 'Yes. Production services — studio hire, field crew, post-production, live streaming, corporate video and podcasts — are booked independently of media buys.' },
      { q: 'How do I reach the newsroom rather than sales?', a: 'Use the Press & Newsroom desk above for tips, corrections, credentials and interview requests. Editorial contacts are separate from the commercial team and enquiries are not shared between them.' },
    ],
    cta: 'Ask something else',
  },
  inquiryTypes: ['Advertising Inquiry', 'Broadcast Partnership', 'Content Partnership', 'Press Credentials', 'Editorial Contact'],
}

export type MediaContent = typeof en
export default en
