import type { ProjectsContent } from './en'

const bn: ProjectsContent = {
  list: {
    breadcrumbHome: 'হোম',
    breadcrumbCurrent: 'আমাদের কাজ',
    eyebrow: 'প্রকল্প ও কেস স্টাডি',
    titleLine1: 'আমাদের কাজ,',
    titleLine2: 'বিস্তারিতভাবে।',
    lead: 'প্রকল্পের ব্রিফ, আমাদের ভূমিকা এবং কী সরবরাহ করা হয়েছে — সবই জানুন। প্রতিটি প্রকল্পের নিজস্ব গল্প আছে।',
    heading: 'আমাদের প্রকল্পগুলো দেখুন',
    searchLabel: 'প্রকল্প খুঁজুন',
    searchPlaceholder: 'প্রকল্প বা সেবা দিয়ে খুঁজুন',
    searchButton: 'খুঁজুন',
    loading: 'প্রকল্প লোড হচ্ছে…',
    errorTitle: 'প্রকল্প লোড করা যায়নি',
    retry: 'আবার চেষ্টা করুন',
    paginationAria: 'প্রকল্পের পৃষ্ঠা',
    previous: 'পূর্ববর্তী',
    next: 'পরবর্তী',
    pageOf: 'পৃষ্ঠা {page} / {total}',
    emptySearchEyebrow: 'অনুসন্ধানের ফলাফল',
    emptyEyebrow: 'প্রকল্পের গল্প',
    emptySearchTitle: 'মিলে যাওয়া কোনো প্রকল্প নেই',
    emptyTitle: 'প্রকল্পের গল্প প্রস্তুত করা হচ্ছে।',
    emptySearchText: 'অন্য কোনো শব্দ দিয়ে চেষ্টা করুন বা অনুসন্ধান মুছে ফেলুন।',
    emptyText: 'প্রকাশের অনুমোদন পাওয়ার সঙ্গে সঙ্গে কেস স্টাডিগুলো এখানে প্রকাশিত হবে। এখন আপনার প্রয়োজনের সঙ্গে প্রাসঙ্গিক অভিজ্ঞতা নিয়ে আমাদের টিমের সঙ্গে কথা বলুন।',
    clearSearch: 'অনুসন্ধান মুছুন',
    talkCta: 'আপনার প্রয়োজন নিয়ে কথা বলুন ↗',
    facts: [
      { v: '10', l: 'কার্যকর বিভাগ' },
      { v: '15+', l: 'সেবা দেওয়া দেশ' },
      { v: '1971', l: 'প্রতিষ্ঠার চেতনা' },
    ],
    filterLabel: 'বিভাগ অনুযায়ী দেখুন',
    filterAll: 'সব কাজ',
    filterClear: 'ফিল্টার মুছুন',
    introEyebrow: 'আলোচনা দিয়ে শুরু করুন',
    introTitle: 'অংশীদারদের অনুমোদনের সঙ্গে সঙ্গে কেস স্টাডি প্রকাশিত হবে।',
    introBody: 'ততদিন, আপনি কী তৈরি, সোর্স বা ডেলিভার করতে চান বলুন — প্রাসঙ্গিক অভিজ্ঞতা আমরা সরাসরি জানাব।',
  },
  detail: {
    loading: 'প্রকল্প লোড হচ্ছে…',
    errorTitle: 'এই প্রকল্প লোড করা যায়নি',
    retry: 'আবার চেষ্টা করুন',
    unavailableEyebrow: 'প্রকল্পটি পাওয়া যাচ্ছে না',
    unavailableTitle: 'এই প্রকল্পটি এখন উপলব্ধ নয়।',
    unavailableText: 'এটি এখনো প্রকাশিত না হতে পারে, অথবা এর লিংক পরিবর্তিত হয়ে থাকতে পারে।',
    browse: 'প্রকল্পসমূহ দেখুন',
    breadcrumbHome: 'হোম',
    breadcrumbList: 'আমাদের কাজ',
    facts: [
      { key: 'client', label: 'ক্লায়েন্ট' },
      { key: 'division', label: 'বিভাগ' },
      { key: 'year', label: 'বছর' },
      { key: 'location', label: 'স্থান' },
      { key: 'duration', label: 'সময়কাল' },
    ],
    deliverablesTitle: 'সরবরাহকৃত কাজ',
    resultEvidenceTitle: 'ফলাফলের প্রমাণ',
    resultBaselineLabel: 'প্রাথমিক অবস্থা / তুলনা',
    resultSourceLabel: 'উৎস / ব্যাখ্যা',
    resultDateLabel: 'যে তারিখ পর্যন্ত',
    galleryTitle: 'প্রকল্পের গ্যালারি',
    testimonialTitle: 'সংশ্লিষ্ট প্রশংসাপত্র',
    publicEvidence: 'প্রকাশ্য প্রমাণ দেখুন ↗',
    story: [
      { key: 'challenge', title: 'চ্যালেঞ্জ' },
      { key: 'role', title: 'আমাদের ভূমিকা ও সরবরাহ' },
      { key: 'results', title: 'ফলাফল' },
    ],
    visitSite: 'প্রকল্পের ওয়েবসাইট দেখুন ↗',
    enquiryEyebrow: 'আপনার পরবর্তী প্রকল্প',
    enquiryTitleLine1: 'এমন কিছু',
    enquiryTitleLine2: 'ভাবছেন কি?',
    enquiryText: 'আপনার প্রয়োজন সম্পর্কে আমাদের জানান এবং ব্রিফে এই প্রকল্পের উল্লেখ করুন।',
    enquiryCta: 'অনুরূপ প্রকল্প নিয়ে আলোচনা করুন ↗',
  },
}

export default bn
