const en = {
  list: {
    breadcrumbHome: 'Home',
    breadcrumbCurrent: 'Our work',
    eyebrow: 'PROJECTS & CASE STUDIES',
    titleLine1: 'Our work,',
    titleLine2: 'in detail.',
    lead: 'Understand the brief, the role we played and what was delivered. Each project has its own story.',
    heading: 'Explore our projects',
    searchLabel: 'Search projects',
    searchPlaceholder: 'Search by project or service',
    searchButton: 'Search',
    loading: 'Loading projects…',
    errorTitle: 'Projects could not be loaded',
    retry: 'Try again',
    paginationAria: 'Project pages',
    previous: 'Previous',
    next: 'Next',
    pageOf: 'Page {page} of {total}',
    emptySearchEyebrow: 'SEARCH RESULTS',
    emptyEyebrow: 'PROJECT STORIES',
    emptySearchTitle: 'No matching projects',
    emptyTitle: 'Project stories are being prepared.',
    emptySearchText: 'Try another keyword or clear your search.',
    emptyText: 'Public case studies will appear here as they are approved for sharing. For now, speak with our team about experience relevant to your requirements.',
    clearSearch: 'Clear search',
    talkCta: 'Talk about your requirements ↗',
  },
  detail: {
    loading: 'Loading project…',
    errorTitle: 'Unable to load this project',
    retry: 'Try again',
    unavailableEyebrow: 'PROJECT UNAVAILABLE',
    unavailableTitle: 'This project is not available.',
    unavailableText: 'It may not be published or its link may have changed.',
    browse: 'Browse projects',
    breadcrumbHome: 'Home',
    breadcrumbList: 'Our work',
    facts: [
      { key: 'client', label: 'Client' },
      { key: 'division', label: 'Division' },
      { key: 'year', label: 'Year' },
      { key: 'location', label: 'Location' },
      { key: 'duration', label: 'Duration' },
    ],
    deliverablesTitle: 'Deliverables',
    resultEvidenceTitle: 'Result evidence',
    resultBaselineLabel: 'Baseline / comparison',
    resultSourceLabel: 'Source / explanation',
    resultDateLabel: 'As of',
    galleryTitle: 'Project gallery',
    testimonialTitle: 'Related testimonial',
    publicEvidence: 'View public evidence ↗',
    story: [
      { key: 'challenge', title: 'The challenge' },
      { key: 'role', title: 'Our role & deliverables' },
      { key: 'results', title: 'The outcome' },
    ],
    visitSite: 'Visit project website ↗',
    enquiryEyebrow: 'YOUR NEXT PROJECT',
    enquiryTitleLine1: 'Have something',
    enquiryTitleLine2: 'similar in mind?',
    enquiryText: 'Tell us about your requirements and reference this project in your brief.',
    enquiryCta: 'Discuss a similar project ↗',
  },
}

export type ProjectsContent = typeof en
export default en
