const en = {
  list: {
    breadcrumbHome: 'Home',
    breadcrumbCurrent: 'Our work',
    eyebrow: 'PROJECTS & CASE STUDIES',
    titleLine1: 'Our work,',
    titleLine2: 'in detail.',
    lead: 'Understand the brief, the role we played and what was delivered. Each project has its own story.',
    heading: 'Explore our projects',
    searchLabel: 'Search projects',
    searchPlaceholder: 'Search by project or service',
    searchButton: 'Search',
    loading: 'Loading projects…',
    errorTitle: 'Projects could not be loaded',
    retry: 'Try again',
    paginationAria: 'Project pages',
    previous: 'Previous',
    next: 'Next',
    pageOf: 'Page {page} of {total}',
    emptySearchEyebrow: 'SEARCH RESULTS',
    emptyEyebrow: 'PROJECT STORIES',
    emptySearchTitle: 'No matching projects',
    emptyTitle: 'Project stories are being prepared.',
    emptySearchText: 'Try another keyword or clear your search.',
    emptyText: 'Public case studies will appear here as they are approved for sharing. For now, speak with our team about experience relevant to your requirements.',
    clearSearch: 'Clear search',
    talkCta: 'Talk about your requirements ↗',
    facts: [
      { v: '10', l: 'Operating divisions' },
      { v: '15+', l: 'Countries served' },
      { v: '1971', l: 'Founding spirit' },
    ],
    filterLabel: 'Browse by division',
    filterAll: 'All work',
    filterClear: 'Clear filter',
    introEyebrow: 'Start with a conversation',
    introTitle: 'Public case studies appear as partners approve them.',
    introBody: 'Until then, tell us what you want to build, source or deliver and we will share relevant experience directly.',
  },
  capabilities: {
    eyebrow: 'What We Deliver',
    title1: 'Work Types,',
    title2: 'by Division',
    lead: 'Case studies are published only with a partner’s consent. The kinds of work we take on, and what a finished engagement typically hands over, are not confidential — here they are.',
    handoverLabel: 'Typical hand-over',
    items: [
      { id: 'garments', types: ['Private-label production runs', 'Sampling & tech-pack development', 'Compliance-audited factory sourcing'], handover: 'Approved samples, PP meeting minutes, inspection reports, shipping documents' },
      { id: 'agriculture', types: ['Commodity export programmes', 'Contract farming & aggregation', 'Cold-chain & post-harvest set-up'], handover: 'Spec sheets, phytosanitary & CoA, season calendar, FCL shipment records' },
      { id: 'food', types: ['Private-label & co-manufacturing', 'New product development (S1–S6)', 'Regional distribution launches'], handover: 'Recipe & spec ownership file, shelf-life data, packaging artwork, first-run QC' },
      { id: 'energy', types: ['Edible-oil import & packing', 'Industrial fuel supply contracts', 'Storage & distribution logistics'], handover: 'CoA per lot, HS documentation, delivery schedules, term-contract paperwork' },
      { id: 'it', types: ['Product discovery & MVP builds', 'Enterprise platforms & ERP', 'AI features & data pipelines'], handover: 'Source code & IP assignment, architecture docs, runbooks, SLA-backed support' },
      { id: 'trading', types: ['Multi-corridor sourcing', 'Export documentation & freight', 'Agency and principal trades'], handover: 'Incoterms-mapped contracts, lane schedule, full document set, inspection certificates' },
      { id: 'media', types: ['Campaigns & sponsorships', 'Production for hire', 'Newsroom partnerships'], handover: 'Media plan & spec sheet, deliverables, audience report, rights schedule' },
      { id: 'ship', types: ['Vessel sale & purchase', 'Recycling sales on LDT basis', 'Inspection & class coordination'], handover: 'MOA, closing document set, PODA, delivery notices' },
      { id: 'ventures', types: ['Joint-venture formation', 'Market-entry programmes', 'Growth investments'], handover: 'Term sheet, SHA/JVA, governance charter, 100-day plan' },
      { id: 'ezyify', types: ['Merchant onboarding', 'Cross-border storefronts', 'Platform integrations'], handover: 'Live storefront, catalogue & payments set-up, analytics access, support desk' },
    ],
    footnote: 'Each division page carries its own commercial terms, specifications and FAQ.',
  },
  standard: {
    eyebrow: 'How a Case Study Is Written',
    title1: 'Every Story Carries',
    title2: 'Its Evidence',
    lead: 'A Network71 case study is not a testimonial. It is published in a fixed shape so a reader can check what was claimed against what was measured.',
    steps: [
      { k: '01', title: 'Consent', desc: 'Written permission from the client or partner before anything is published. No consent, no story — even for finished work.' },
      { k: '02', title: 'Brief & role', desc: 'The challenge in the client’s terms, the role Network71 played, and what was explicitly out of scope.' },
      { k: '03', title: 'Deliverables', desc: 'A checklist of what was handed over, matching the division’s typical hand-over set.' },
      { k: '04', title: 'Result evidence', desc: 'Each result states a baseline or comparison, the source or method, and an “as of” date. Public evidence is linked where it exists.' },
      { k: '05', title: 'Review', desc: 'The partner reviews the draft; disputed figures are removed rather than softened.' },
    ],
    exampleLabel: 'Result block, as published',
    example: { metric: '−18 % lead time', baseline: 'Baseline: 2023 season average, same factory', source: 'Source: shipment log, 41 orders; method note attached', date: 'As of: Mar 2025' },
    footnote: 'The result-evidence fields shown here are the ones every project detail page renders.',
  },
  faq: {
    eyebrow: 'Working With Us',
    title1: 'Before You',
    title2: 'Send a Brief',
    lead: 'Answers to the questions we hear before a first project.',
    items: [
      { q: 'Why are there so few public case studies?', a: 'Because we only publish with the client’s written consent and with evidence attached. Much of our work is under NDA or for partners who prefer not to be named. We share relevant, anonymised experience directly in conversation.' },
      { q: 'Can I see references before committing?', a: 'Yes. Once the scope is clear we arrange a reference call with a comparable client in the same division, subject to their availability.' },
      { q: 'Do you take projects outside your ten divisions?', a: 'Rarely. If a brief sits between divisions — for example agro sourcing plus export logistics plus a digital storefront — we assemble a cross-division team. Work with no fit to any division is usually referred elsewhere.' },
      { q: 'How should I structure a brief?', a: 'Goal, constraints (budget range, timeline, location, compliance), what you will supply, and how you will judge success. Two pages is plenty; the discovery call fills the gaps.' },
      { q: 'What does a first conversation cost?', a: 'Nothing. Discovery calls and an indicative proposal are free. Paid engagement starts when a scope and commercial terms are agreed in writing.' },
      { q: 'Who owns what we build together?', a: 'It is written into the contract. For software, IP assignment to the client at final payment is our default. For product and sourcing work, formulas, tech packs and supplier lists follow the terms in the division’s commercial ledger.' },
      { q: 'Can my project become a case study?', a: 'Only if you want it to. We will ask at close-out, you approve the draft, and you can withdraw consent later — the story comes down.' },
    ],
    cta: 'Send a brief',
  },
  detail: {
    loading: 'Loading project…',
    errorTitle: 'Unable to load this project',
    retry: 'Try again',
    unavailableEyebrow: 'PROJECT UNAVAILABLE',
    unavailableTitle: 'This project is not available.',
    unavailableText: 'It may not be published or its link may have changed.',
    browse: 'Browse projects',
    breadcrumbHome: 'Home',
    breadcrumbList: 'Our work',
    facts: [
      { key: 'client', label: 'Client' },
      { key: 'division', label: 'Division' },
      { key: 'year', label: 'Year' },
      { key: 'location', label: 'Location' },
      { key: 'duration', label: 'Duration' },
    ],
    deliverablesTitle: 'Deliverables',
    resultEvidenceTitle: 'Result evidence',
    resultBaselineLabel: 'Baseline / comparison',
    resultSourceLabel: 'Source / explanation',
    resultDateLabel: 'As of',
    galleryTitle: 'Project gallery',
    testimonialTitle: 'Related testimonial',
    publicEvidence: 'View public evidence ↗',
    story: [
      { key: 'challenge', title: 'The challenge' },
      { key: 'role', title: 'Our role & deliverables' },
      { key: 'results', title: 'The outcome' },
    ],
    visitSite: 'Visit project website ↗',
    enquiryEyebrow: 'YOUR NEXT PROJECT',
    enquiryTitleLine1: 'Have something',
    enquiryTitleLine2: 'similar in mind?',
    enquiryText: 'Tell us about your requirements and reference this project in your brief.',
    enquiryCta: 'Discuss a similar project ↗',
  },
}

export type ProjectsContent = typeof en
export default en
