<?php
declare(strict_types=1);

// One server-owned contract drives validation and the admin form fields.
$field = static fn(string $key, string $label, string $type = 'text', bool $required = false, array $options = []): array => compact('key', 'label', 'type', 'required', 'options');
$title = $field('title', 'Title', 'text', true);
$summary = $field('summary', 'Short introduction', 'textarea');
$body = $field('body', 'Main content', 'textarea');
$image = $field('image', 'Cover image URL', 'image');
$seo = [$field('seo_title', 'Search engine title'), $field('seo_description', 'Search engine description', 'textarea')];
$module = static fn(string $label, string $description, array $fields): array => compact('label', 'description', 'fields');

return [
    'projects' => $module('Projects', 'Document real work, delivery evidence and publication permission.', [$title, $summary, $image, $field('division', 'Division'), $field('client', 'Approved client name / Confidential client'), $field('type', 'Project type', 'select', true, ['Client work', 'Own product', 'Internal initiative']), $field('work_status', 'Work status', 'select', true, ['Completed', 'Ongoing', 'Concept']), $field('year', 'Delivery year'), $field('location', 'Project location'), $field('duration', 'Project duration'), $field('challenge', 'Client challenge', 'textarea'), $field('role', 'Our role', 'textarea', true), $field('deliverables', 'Deliverables (one per line)', 'textarea'), $field('results', 'Verified results', 'textarea'), $field('result_baseline', 'Result baseline / comparison', 'textarea'), $field('result_source', 'Public result source / explanation', 'textarea'), $field('result_date', 'Results as-of date', 'date'), $field('gallery_images', 'Project image URLs (one per line)', 'urls'), $field('gallery_captions', 'Image captions (one per line, matching image order)', 'textarea'), $field('testimonial_quote', 'Related approved testimonial', 'textarea'), $field('testimonial_attribution', 'Testimonial attribution'), $field('evidence_label', 'Public evidence link label'), $field('evidence_url', 'Public evidence URL', 'url'), $field('url', 'Live project link', 'url'), $field('permission', 'Client, evidence and media publication permission confirmed', 'checkbox', true), ...$seo]),
    'team' => $module('Team', 'Leadership and team profiles approved for publication.', [$title, $field('position', 'Position', 'text', true), $body, $image, $field('url', 'Professional profile link', 'url')]),
    'posts' => $module('Insights', 'Articles and business updates.', [$title, $summary, $body, $image, $field('author', 'Author'), $field('date', 'Article date', 'date'), ...$seo]),
    'press' => $module('Press', 'Official announcements and press coverage.', [$title, $summary, $body, $image, $field('date', 'Publication date', 'date'), $field('url', 'Source link', 'url'), ...$seo]),
    'jobs' => $module('Careers', 'Open positions and how candidates should apply.', [$title, $field('location', 'Location'), $field('employment', 'Employment type', 'select', true, ['Full time', 'Part time', 'Contract', 'Internship']), $body, $field('deadline', 'Application deadline', 'date'), $field('email', 'Application email', 'email', true)]),
    'gallery' => $module('Gallery', 'Real company and project images with accurate captions.', [$title, $image, $field('caption', 'Caption', 'textarea'), $field('division', 'Division')]),
    'brands' => $module('Brands & products', 'Your businesses and products, with accurate launch status.', [$title, $summary, $image, $field('url', 'Website', 'url'), $field('stage', 'Stage', 'select', true, ['Operating', 'In development', 'Concept'])]),
    'locations' => $module('Global presence', 'Approved offices and operating locations.', [$title, $field('country', 'Country'), $field('address', 'Address', 'textarea'), $field('presence', 'Presence type', 'select', true, ['Office', 'Trade market', 'Partner location']), $field('email', 'Contact email', 'email'), $field('phone', 'Phone')]),
    'timeline' => $module('Timeline', 'Documented company milestones.', [$title, $field('date', 'Milestone date', 'date', true), $body, $image]),
    'testimonials' => $module('Testimonials', 'Client feedback with permission to publish.', [$title, $field('position', 'Client position / company'), $field('quote', 'Approved quote', 'textarea', true), $image, $field('permission', 'Client has approved this public quote', 'checkbox', true)]),
    'credentials' => $module('Credentials', 'Certifications with issuer, validity and verification source.', [$title, $field('issuer', 'Issuer', 'text', true), $field('reference', 'Certificate reference'), $field('expires', 'Expiry date', 'date'), $field('url', 'Verification URL', 'url'), $image]),
    'metrics' => $module('Verified metrics', 'Publish only figures supported by company records.', [$title, $field('value', 'Display value', 'text', true), $field('source', 'Public source or explanation', 'textarea', true), $field('date', 'As of date', 'date', true)]),
    'navigation' => $module('Navigation', 'Header and footer link labels, destinations and display order.', [$title, $field('url', 'Link destination', 'link', true), $field('placement', 'Placement', 'select', true, ['Header', 'Footer'])]),
    'settings' => $module('Company settings', 'Publish one company-profile record for shared contact details. Public business information only; never enter passwords or SMTP secrets.', [$title, $summary, $field('email', 'General contact email', 'email'), $field('careers_email', 'Careers email', 'email'), $field('press_email', 'Press email', 'email'), $field('legal_email', 'Legal email', 'email'), $field('investors_email', 'Investor relations email', 'email'), $field('phone', 'Contact phone'), $field('address', 'Operating address', 'textarea'), $field('registered_address', 'Registered address', 'textarea'), $field('business_hours', 'Business hours'), $field('website', 'Main website', 'url'), $field('linkedin', 'LinkedIn profile', 'url'), $field('facebook', 'Facebook profile', 'url'), $field('youtube', 'YouTube channel', 'url'), $field('x', 'X profile', 'url'), $image]),
];
