CREATE TABLE job_applications (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    reference VARCHAR(30) NOT NULL UNIQUE,
    job_record_id BIGINT UNSIGNED NULL,
    job_slug VARCHAR(160) NOT NULL,
    job_title VARCHAR(255) NOT NULL,
    locale VARCHAR(5) NOT NULL DEFAULT 'en',
    name VARCHAR(120) NOT NULL,
    email VARCHAR(190) NOT NULL,
    phone VARCHAR(40) NOT NULL DEFAULT '',
    cover_letter TEXT NOT NULL,
    consent_at DATETIME NOT NULL,
    request_key VARCHAR(64) NOT NULL UNIQUE,
    request_hash CHAR(64) NOT NULL,
    resume_filename VARCHAR(100) NOT NULL UNIQUE,
    resume_original_name VARCHAR(255) NOT NULL,
    resume_mime VARCHAR(40) NOT NULL,
    resume_bytes INT UNSIGNED NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'new',
    assigned_to BIGINT UNSIGNED NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    KEY applications_status (status, created_at),
    KEY applications_assignee (assigned_to, status),
    CONSTRAINT applications_job_fk FOREIGN KEY (job_record_id) REFERENCES content_records(id) ON DELETE SET NULL,
    CONSTRAINT applications_assignee_fk FOREIGN KEY (assigned_to) REFERENCES admin_users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
