import { INDIGO, GOLD } from '../theme'

const en = {
  divisionName: 'Strategic Ventures',
  hero: {
    eyebrow: 'Network71 — Division 08',
    badge: 'International Business & Strategic Ventures',
    title1: 'Where New Businesses',
    title2: 'Take Shape.',
    lead: "The diversified business platform of Network71 — identifying new opportunities across industries, structuring joint ventures and strategic partnerships, and taking the group's divisions into new international markets.",
    ctaPrimary: 'Propose a Venture',
    ctaSecondary: 'How We Partner',
    mapEyebrow: 'Ecosystem access',
    mapCount: '{n} operating divisions',
    mapNote: 'Every venture can draw on manufacturing, sourcing, logistics, technology, media and maritime capability inside the group.',
  },
  metrics: [
    { value: '10', label: 'Divisions', desc: 'One connected ecosystem' },
    { value: 'JV', label: 'Structures', desc: 'Joint ventures & partnerships' },
    { value: 'Multi', label: 'Sector', desc: 'Cross-industry opportunity scope' },
    { value: 'Global', label: 'Expansion', desc: 'New markets & corridors' },
  ],
  overview: {
    eyebrow: 'Division Overview',
    title: 'A Diversified Platform for What Comes Next',
    p1: "Network71 grows in two ways: by strengthening each operating division, and by creating new businesses where an opportunity, a partner and the group's capabilities meet. The International Business & Strategic Ventures division owns the second path.",
    p2: 'It evaluates opportunities across industries, structures joint ventures and strategic partnerships, and leads international expansion — so that the whole ecosystem, not just one division, benefits from every new market we enter.',
    principles: [
      { title: 'Aligned Incentives', desc: 'We only enter structures where partners win together — shared upside, shared accountability.' },
      { title: 'Operational Depth', desc: "Every venture is backed by the group's divisions, not just capital. Manufacturing, trade, tech and media resources are on call." },
      { title: 'Governance First', desc: 'Clear boards, reporting lines and decision rights from the start. No ambiguity in ownership or control.' },
      { title: 'Long-term Horizon', desc: 'We build businesses to last. Short-term arbitrage is not our model.' },
    ],
  },
  models: {
    eyebrow: 'How We Partner',
    title: 'Six Ways to Build Together',
    lead: 'From co-owned operating companies to market-entry programmes, each structure is chosen to fit the opportunity — never the other way round.',
    items: [
      { id: 'jv', title: 'Joint Ventures', desc: 'Co-owned operating companies with aligned partners — shared capital, shared governance, and a clear operating plan from day one.', color: INDIGO },
      { id: 'partnership', title: 'Strategic Partnerships', desc: "Long-term commercial alliances — distribution, sourcing, technology or market-access agreements that extend both partners' reach.", color: GOLD },
      { id: 'entry', title: 'Market Entry', desc: 'Structured expansion of Network71 divisions into new countries: regulatory mapping, local partners, entity setup and launch support.', color: 'var(--accent-cyan)' },
      { id: 'growth', title: 'Growth Investment', desc: 'Minority or majority positions in businesses that complement the ecosystem — with operational support rather than passive capital.', color: 'var(--accent-emerald)' },
      { id: 'corridor', title: 'Trade Corridors', desc: 'Bilateral business platforms connecting Bangladesh with the Middle East, Europe, East Asia and Africa across multiple divisions.', color: 'var(--accent-sky)' },
      { id: 'incubation', title: 'Incubation & Spin-outs', desc: 'New ventures born inside the group — validated, resourced and spun out as independent businesses when they are ready.', color: 'var(--accent-purple)' },
    ],
  },
  processLabel: 'From Opportunity to Operating Business',
  process: [
    { title: 'Opportunity Screening', desc: 'Sector fit, market size, partner credibility and alignment with the wider Network71 ecosystem.' },
    { title: 'Due Diligence', desc: 'Commercial, financial, legal and reputational review before any commitment is made.' },
    { title: 'Structure & Terms', desc: 'JV, partnership or investment structure; governance, capital plan and exit provisions.' },
    { title: 'Formation', desc: 'Entity setup, regulatory approvals, banking and operating agreements.' },
    { title: 'Launch & Operate', desc: 'Management team, shared services from the group and quarterly performance reviews.' },
    { title: 'Scale', desc: 'Expansion into new products, geographies or adjacent divisions once fundamentals are proven.' },
  ],
  partners: {
    eyebrow: 'Who We Work With',
    title: 'Partners Who Want to Build, Not Just Transact',
    lead: 'We look for partners with real operating intent and a long-term view. If you have a business, a technology or a market and want a committed counterpart in Bangladesh and South Asia, this is the division to speak with.',
    cta: 'Start a Conversation',
    items: [
      { title: 'Industrial Groups', desc: 'Manufacturers and producers seeking a Bangladesh or South Asia partner with local operating capability.' },
      { title: 'Technology Companies', desc: 'Platforms and software businesses looking for distribution, localisation or a regional operating base.' },
      { title: 'Investors & Family Offices', desc: 'Capital partners who want exposure to a diversified, operator-led emerging-market portfolio.' },
      { title: 'Government & Trade Bodies', desc: 'Bilateral trade and investment programmes connecting markets through structured business platforms.' },
    ],
  },
  status: {
    title: 'Active ventures are published as they are approved',
    p: 'We do not list partners, deals or portfolio companies until both sides have agreed to public disclosure. Approved ventures and case studies appear in ',
    link: 'Our Work',
    p2: '.',
    cta: 'Investor Relations →',
  },
  mandate: {
    eyebrow: 'Investment Mandate',
    title1: 'What We Look For,',
    title2: 'in Numbers',
    lead: 'The frame a partner or founder asks about first. Indicative — every venture is sized to its own plan.',
    facts: [
      { value: '0.5–10', unit: ' M USD', label: 'Ticket range', sub: 'Equity or capital commitment per venture; larger with co-investors' },
      { value: '20–60', unit: ' %', label: 'Target stake', sub: 'Significant minority to controlling; always with operating involvement' },
      { value: '5–10', unit: ' yrs', label: 'Holding horizon', sub: 'We build to operate; exits are planned, not forced' },
      { value: '10', unit: ' divisions', label: 'Ecosystem access', sub: 'Manufacturing, sourcing, logistics, tech, media and maritime on call' },
      { value: '90', unit: ' days', label: 'Screen to term sheet', sub: 'Typical elapsed time when data-room and partner are ready' },
      { value: '4', unit: ' regions', label: 'Corridor focus', sub: 'Bangladesh ↔ GCC, Europe, East & Southeast Asia, Africa' },
    ],
    note: 'Indicative planning frame; each engagement is set out in a term sheet after due diligence.',
    cta: 'Propose a venture',
  },
  structures: {
    eyebrow: 'Structure Comparison',
    title1: 'Which Structure',
    title2: 'Fits the Opportunity',
    lead: 'How ownership, governance, capital and exit typically work under each model. We pick the structure after the thesis is clear — never before.',
    rows: ['Ownership', 'Governance', 'Capital', 'Operations', 'Exit'],
    models: [
      { code: 'JV', name: 'Joint Venture', cells: ['Co-owned NewCo, 30–70 % N71', 'Joint board, reserved matters, deadlock clause', 'Shared per stake; milestone tranches', 'Dedicated management, group shared services', 'Put/call options, ROFR, IPO or trade sale'] },
      { code: 'SP', name: 'Strategic Partnership', cells: ['No equity; commercial agreement', 'Steering committee, quarterly review', 'Each side funds its own scope', 'Distribution, sourcing or tech licence', 'Term-based; renewal or conversion to JV'] },
      { code: 'GI', name: 'Growth Investment', cells: ['Minority 20–49 % in existing company', 'Board seat, information & consent rights', 'Primary or secondary; follow-on rights', 'Founder-led; N71 operational support', '5–7 yr horizon; secondary, strategic sale'] },
      { code: 'ME', name: 'Market Entry', cells: ['N71 division subsidiary or local JV', 'Division board with local partner rights', 'N71 funds entity; partner contributes access', 'Local partner operates; division supplies product', 'Buy-out of partner or long-term JV'] },
      { code: 'TC', name: 'Trade Corridor', cells: ['Bilateral platform company', 'Joint council with trade bodies', 'Programme funding + transaction fees', 'Corridor team across divisions', 'Evergreen; spin-out of sub-ventures'] },
      { code: 'IN', name: 'Incubation', cells: ['100 % N71 at start; founder equity vesting', 'Internal venture board', 'Staged internal funding', 'Founding team + group resources', 'Spin-out with external round or absorb'] },
    ],
    footnote: 'Typical positions; every term is negotiated and set out in the shareholders’ or partnership agreement.',
  },
  timeline: {
    eyebrow: 'Deal Timeline',
    title1: 'From First Call',
    title2: 'to Signed Agreement',
    lead: 'What happens in each window, what we need from you, and what you receive back — so no stage is a black box.',
    stages: [
      { code: 'W1', title: 'Intro & thesis', window: 'Week 1–2', we: 'Two-page opportunity note: market, edge, ask', you: 'Deck or one-pager, headline numbers, partner intent', out: 'Go / no-go to screen' },
      { code: 'W2', title: 'Screening', window: 'Week 2–4', we: 'Sector fit, ecosystem synergies, partner references', you: 'Management call, customer or supplier references', out: 'Screening memo + indicative structure' },
      { code: 'W3', title: 'Due diligence', window: 'Week 4–10', we: 'Commercial, financial, legal, reputational and ESG review', you: 'Data room, site visit, key-person interviews', out: 'DD report + valuation range' },
      { code: 'W4', title: 'Term sheet', window: 'Week 10–13', we: 'Structure, governance, capital plan, exit provisions', you: 'Board / shareholder approvals in principle', out: 'Signed term sheet, exclusivity' },
      { code: 'W5', title: 'Definitive agreements', window: 'Week 13–20', we: 'SHA / JVA drafting, regulatory filings, banking', you: 'Legal counsel, corporate authorisations, funding readiness', out: 'Signing and conditions precedent' },
      { code: 'W6', title: 'Formation & launch', window: 'Week 20+', we: 'Entity setup, management team, shared-services onboarding', you: 'Operational handover, first 100-day plan', out: 'Operating business, quarterly reviews' },
    ],
    labels: { we: 'We do', you: 'You provide', out: 'You receive' },
    footnote: 'Indicative for a mid-size JV with a ready data room; cross-border regulatory approvals can extend weeks 13–20.',
  },
  readiness: {
    eyebrow: 'Partner Readiness',
    title1: 'What Speeds a Deal Up',
    title2: '— and What Slows It Down',
    lead: 'Have these ready and screening to term sheet can run inside 90 days.',
    groups: [
      { title: 'Commercial', items: ['Three-year historic financials or credible model', 'Top-10 customer / supplier list with concentration', 'Market sizing with the source of every number', 'Pricing, margins and unit economics by product'] },
      { title: 'Legal & governance', items: ['Cap table and corporate documents', 'Material contracts and any change-of-control clauses', 'Licences, permits, IP ownership', 'Litigation, tax and compliance disclosures'] },
      { title: 'People & operations', items: ['Management CVs and key-person dependencies', 'Organisation chart and headcount plan', 'Site, capacity and utilisation data', 'ESG, labour and safety practices'] },
    ],
    cta: 'Request the data-room index',
  },
  faq: {
    eyebrow: 'Partner FAQ',
    title1: 'Before You',
    title2: 'Propose a Venture',
    lead: 'Straight answers on what we back, how control works, how long it takes and what happens when a venture does not work out.',
    items: [
      { q: 'What kind of ventures do you back?', a: 'Operating businesses that gain from the Network71 ecosystem — manufacturing, sourcing, logistics, technology, media or maritime — where a credible partner brings market, technology or capability we do not have. We do not back passive financial positions or ventures that compete directly with an existing division.' },
      { q: 'Do you need control?', a: 'No. We need operating involvement and clear governance — a board seat, reserved matters and information rights — at whatever stake fits the venture. Stakes range from significant minority to controlling depending on who runs the business day to day.' },
      { q: 'How long does it take to get to a signed agreement?', a: 'Around 90 days from first call to term sheet when the data room and partner approvals are ready, and a further 7–10 weeks to definitive agreements. Cross-border regulatory approvals are the usual reason a timeline stretches.' },
      { q: 'What does Network71 contribute beyond capital?', a: 'Shared services (finance, legal, HR, technology), access to ten divisions for supply, distribution and channels, corridor relationships in the GCC, Europe, Asia and Africa, and an operating management bench. Contributions are set out in the term sheet as obligations, not intentions.' },
      { q: 'How are decisions and disputes handled?', a: 'A joint board with reserved matters for major decisions, quarterly performance reviews against the agreed plan, and a deadlock mechanism — escalation, mediation, then put/call — written into the shareholders’ agreement from day one.' },
      { q: 'What is the exit plan?', a: 'Agreed at term-sheet stage: put/call options at a formula or fair value, rights of first refusal, and a target horizon of five to ten years. We prefer to build businesses that keep operating; an exit is a planned event, not a rescue.' },
      { q: 'Do you publish your portfolio?', a: 'Only with both parties’ consent. Approved ventures and case studies appear under Our Work; pipeline and unannounced deals are never listed.' },
    ],
    cta: 'Ask something else',
  },
  inquiryTypes: ['Joint Venture Proposal', 'Strategic Partnership', 'Market Entry', 'Investment Opportunity', 'Trade Corridor / Bilateral'],
}

export type VenturesContent = typeof en
export default en
